#!/usr/bin/env bash


##############################################################################
#                            GENERAL CONFIGURATION                           #
##############################################################################
bspc config border_width         1 
bspc config window_gap           2

bspc config top_padding          0
bspc config bottom_padding       0

# from https://draculatheme.com/bspwm/
# bspc config active_border_color "#6272a4"
# bspc config focused_border_color "#8be9fd"
# bspc config normal_border_color "#44475a"
# bspc config presel_feedback_color "#6272a4" 

bspc config active_border_color     "#44475a"
bspc config focused_border_color    "#44475a"
bspc config normal_border_color     "#44475a"
bspc config presel_feedback_color   "#6272a4"

bspc config automatic_scheme alternate 
bspc config initial_polarity second_child
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true


bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

##############################################################################
#                                 WINDOW RULES                               #
##############################################################################
bspc rule -a Blueman-manager            state=floating
bspc rule -a KeePassXC                  state=floating
bspc rule -a netease-cloud-music        state=floating
bspc rule -a realvnc-vncviewer          state=floating
bspc rule -a wechat.exe                 state=floating
bspc rule -a wxwork.exe                 state=floating
bspc rule -a youtube-music-desktop-app  state=floating
bspc rule -a Org.gnome.Nautilus         state=floating
bspc rule -a Zathura                    state=floating
bspc rule -a Seahorse                   state=floating
bspc rule -a Evolution                  state=floating
bspc rule -a Liferea                    state=floating
bspc rule -a Evolution-alarm-notify     state=floating
bspc rule -a Wine                       state=floating
bspc rule -a cloudmusic.exe             state=floating
bspc rule -a org.gnome.clocks 		    state=floating
bspc rule -a xfreerdp                   state=tiled
##############################################################################
#                                Monitors                                    #
##############################################################################
monitors=(`xrandr -q | grep " connected" | awk '{print $1}'`)

if [ ${#monitors[@]} -eq 1 ] ; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0 a b
elif [ ${#monitors[@]} -eq 2 ] ; then
    xrandr --output DP1 --primary --mode 1920x1080 --pos 0x315 --rotate normal \
	--output HDMI1 --off \
	--output HDMI2 --mode 1920x1080 --pos 1920x0 --rotate left  \
	--output HDMI3 --off

    bspc monitor ${monitors[0]} -d 1 2 3 4 5
    bspc monitor ${monitors[1]} -d 6 7 8 9 0 a b 
fi


# launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

