---
# tasks file for bspwm
- name: Install packages
  become: yes
  apt:
    pkg:
      - bspwm
    state: latest

- name: Create directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/bspwm"
    state: directory
    mode: '755'

- name: copy .config/bspwm/bspwmrc
  ansible.builtin.copy:
    src: bspwmrc
    dest: "{{ ansible_env.HOME }}/.config/bspwm"
    mode: '755'
