---
# tasks file for alacritty
- name: Install alacritty
  become: yes
  apt:
    pkg:
      - alacritty
      - fonts-jetbrains-mono
    state: latest

- name: Create directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: '755'

- name: copy .config/alacritty/alacritty.yml
  ansible.builtin.copy:
    src: alacritty.yml
    dest: "{{ ansible_env.HOME }}/.config/alacritty"
    mode: '666'
